// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicletelemetry.proto

#include "vehicletelemetry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_common_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TelemetryReading_common_2eproto;
namespace com {
namespace bosch {
namespace itrams_gen2e {
class TelemetryPayloadDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TelemetryPayload> _instance;
} _TelemetryPayload_default_instance_;
}  // namespace itrams_gen2e
}  // namespace bosch
}  // namespace com
static void InitDefaultsscc_info_TelemetryPayload_vehicletelemetry_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::bosch::itrams_gen2e::_TelemetryPayload_default_instance_;
    new (ptr) ::com::bosch::itrams_gen2e::TelemetryPayload();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::bosch::itrams_gen2e::TelemetryPayload::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TelemetryPayload_vehicletelemetry_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_TelemetryPayload_vehicletelemetry_2eproto}, {
      &scc_info_TelemetryReading_common_2eproto.base,}};

namespace com {
namespace bosch {
namespace itrams_gen2e {

// ===================================================================

void TelemetryPayload::InitAsDefaultInstance() {
}
class TelemetryPayload::_Internal {
 public:
};

void TelemetryPayload::clear_measures() {
  measures_.Clear();
}
TelemetryPayload::TelemetryPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena),
  measures_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.bosch.itrams_gen2e.TelemetryPayload)
}
TelemetryPayload::TelemetryPayload(const TelemetryPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      measures_(from.measures_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.bosch.itrams_gen2e.TelemetryPayload)
}

void TelemetryPayload::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TelemetryPayload_vehicletelemetry_2eproto.base);
}

TelemetryPayload::~TelemetryPayload() {
  // @@protoc_insertion_point(destructor:com.bosch.itrams_gen2e.TelemetryPayload)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void TelemetryPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void TelemetryPayload::ArenaDtor(void* object) {
  TelemetryPayload* _this = reinterpret_cast< TelemetryPayload* >(object);
  (void)_this;
}
void TelemetryPayload::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TelemetryPayload::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TelemetryPayload& TelemetryPayload::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TelemetryPayload_vehicletelemetry_2eproto.base);
  return *internal_default_instance();
}


void TelemetryPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:com.bosch.itrams_gen2e.TelemetryPayload)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  measures_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* TelemetryPayload::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .com.bosch.itrams_gen2e.TelemetryReading measures = 1[json_name = "measures"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_measures(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TelemetryPayload::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.bosch.itrams_gen2e.TelemetryPayload)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .com.bosch.itrams_gen2e.TelemetryReading measures = 1[json_name = "measures"];
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_measures_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_measures(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.bosch.itrams_gen2e.TelemetryPayload)
  return target;
}

size_t TelemetryPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.bosch.itrams_gen2e.TelemetryPayload)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .com.bosch.itrams_gen2e.TelemetryReading measures = 1[json_name = "measures"];
  total_size += 1UL * this->_internal_measures_size();
  for (const auto& msg : this->measures_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TelemetryPayload::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const TelemetryPayload*>(
      &from));
}

void TelemetryPayload::MergeFrom(const TelemetryPayload& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.bosch.itrams_gen2e.TelemetryPayload)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  measures_.MergeFrom(from.measures_);
}

void TelemetryPayload::CopyFrom(const TelemetryPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.bosch.itrams_gen2e.TelemetryPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TelemetryPayload::IsInitialized() const {
  return true;
}

void TelemetryPayload::InternalSwap(TelemetryPayload* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  measures_.InternalSwap(&other->measures_);
}

std::string TelemetryPayload::GetTypeName() const {
  return "com.bosch.itrams_gen2e.TelemetryPayload";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace itrams_gen2e
}  // namespace bosch
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::bosch::itrams_gen2e::TelemetryPayload* Arena::CreateMaybeMessage< ::com::bosch::itrams_gen2e::TelemetryPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::bosch::itrams_gen2e::TelemetryPayload >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
