apiVersion: v1
kind: Service
metadata:
  name: my-cpp-microservice-service
spec:
  type: NodePort
  selector:
    app: my-cpp-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
